apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-frontend
  namespace: user1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tienda-frontend
  template:
    metadata:
      labels:
        app: tienda-frontend
    spec:
      containers:
      - name: frontend
        image: localhost:5000/tienda-frontend:eks-v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"
